In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [2]:
plant_data=pd.read_csv('/content/plant_disease_dataset.csv')

In [3]:
plant_data.head()

temperature   humidity   rainfall   soil_pH  disease_present
0    27.483571  33.215053   0.572758  4.975875                1
1    24.308678  36.945005  42.522346  8.165266                0
2    28.238443  34.026189  16.095303  6.316734                1
3    32.615149  41.104180  20.311015  6.164949                0
4    23.829233  51.971785  11.851323  8.482468                0

In [4]:
#number of rows and columns in this dataset
plant_data.shape

(10000, 5)

In [5]:
#getting the statistical measures of the dataset
plant_data.describe()

temperature      humidity      rainfall       soil_pH  disease_present
count  10000.000000  10000.000000  10000.000000  10000.000000     10000.000000
mean      25.612191     62.119300      9.807522      6.245855         0.241000
std        5.813841     22.679977      9.852130      1.302465         0.427712
min        5.387999      6.244209      0.000055      4.000075         0.000000
25%       21.815610     40.772925      2.812822      5.122970         0.000000
50%       25.293238     72.211752      6.864898      6.232188         0.000000
75%       28.916048     81.032999     13.442871      7.386377         0.000000
max       56.686495    102.395421     84.654161      8.499875         1.000000

In [6]:
plant_data['disease_present'].value_counts()

disease_present
0    7590
1    2410
Name: count, dtype: int64

0 --> No Disease

1 --> Disease


In [7]:
plant_data.groupby('disease_present').mean()

temperature   humidity   rainfall   soil_pH
disease_present                                             
0                  25.615038  59.573134   8.593994  6.300228
1                  25.603225  70.138138  13.629382  6.074615

In [9]:
#separating the data and labels
X= plant_data.drop(columns='disease_present', axis=1)
Y= plant_data['disease_present']

In [10]:
print(X)
print(Y)

      temperature   humidity   rainfall   soil_pH
0       27.483571  33.215053   0.572758  4.975875
1       24.308678  36.945005  42.522346  8.165266
2       28.238443  34.026189  16.095303  6.316734
3       32.615149  41.104180  20.311015  6.164949
4       23.829233  51.971785  11.851323  8.482468
...           ...        ...        ...       ...
9995    31.505510  81.939137  22.406822  5.862952
9996    15.008275  86.886833  10.503881  4.070539
9997    21.473416  81.891770  13.426869  7.101583
9998    27.478828  88.567649   9.719659  7.732620
9999    28.221942  71.900401   4.886391  4.383536

[10000 rows x 4 columns]
0       1
1       0
2       1
3       0
4       0
       ..
9995    1
9996    0
9997    0
9998    0
9999    0
Name: disease_present, Length: 10000, dtype: int64


In [11]:
scaler = StandardScaler()

In [12]:
scaler.fit(X)

StandardScaler()

In [13]:
standard_data=scaler.transform(X)

In [14]:
print(standard_data)

[[ 0.32189968 -1.27450275 -0.93738372 -0.97510765]
 [-0.22421968 -1.11003436  3.32074982  1.47374945]
 [ 0.45174666 -1.23873652  0.63824726  0.05442193]
 ...
 [-0.7119186   0.87184652  0.36738525  0.65703976]
 [ 0.32108385  1.16621246 -0.0089187   1.14155865]
 [ 0.44890839  0.43128749 -0.49952425 -1.42991329]]


In [15]:
X = standard_data
Y = plant_data['disease_present']

In [16]:
print(X)
print(Y)

[[ 0.32189968 -1.27450275 -0.93738372 -0.97510765]
 [-0.22421968 -1.11003436  3.32074982  1.47374945]
 [ 0.45174666 -1.23873652  0.63824726  0.05442193]
 ...
 [-0.7119186   0.87184652  0.36738525  0.65703976]
 [ 0.32108385  1.16621246 -0.0089187   1.14155865]
 [ 0.44890839  0.43128749 -0.49952425 -1.42991329]]
0       1
1       0
2       1
3       0
4       0
       ..
9995    1
9996    0
9997    0
9998    0
9999    0
Name: disease_present, Length: 10000, dtype: int64


In [17]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [18]:
print(X.shape, X_train.shape, X_test.shape)

(10000, 4) (8000, 4) (2000, 4)


In [19]:
classifier = svm.SVC(kernel='linear')

In [20]:
#training the support vector machine Classifier
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

Accuracy Score


Model Evaluation

In [22]:
#accuracy score on training data
X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [23]:
print('Accuracy score of the training data :',training_data_accuracy)

Accuracy score of the training data : 0.759


In [25]:
#accuracy score on test data
X_test_prediction = classifier.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [27]:
print('Accuracy score of the testing data :',testing_data_accuracy)

Accuracy score of the testing data : 0.759


Making Predictive Model

In [28]:
input_data=(27.712800217929825,48.18594618343214,3.063415847672062,4.42677861557573)

#changing input data into numpy array
input_data_as_numpy_array=np.asarray(input_data)

#reshape the array as we are predicting for one instance
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

std_data=scaler.transform(input_data_reshaped)

prediction = classifier.predict(std_data)
print(prediction)

if(prediction[0]==0):
  print('The plant is good')
else:
  print('Plant has Disease')

[0]
The plant is Healty
